### ISSUE TITLE
Need to press enter twice when checking in

### ISSUE THREAD

**Issue by sancharib-git** [AY1920S2-CS2103T-W13-2/main#224] opened 2020-04-10 14:25 UTC
Bug where user needs to press enter twice when checking in a guest for the UI to show change in status of room. This happens when size of booking list = 1

**Comment by dawidjaja** [comment] 2020-04-12 07:09
I will close this since I can't reproduce it in the master.

**Closed as completed by dawidjaja** 2020-04-12 07:09 UTC
